### PR TITLE
Manage api keys

### PR DESCRIPTION
**Pull request by MBuchalik**
This PR:
- Implements the features described in #7 
- Adds a Service that allows us to create Snackbars (i.e. Toasts) programmatically. Before, it was only possible to create Snackbars using the `<Snackbar />` component, which leads to quite a lot of code and which is often simply not possible (e.g. when the containing component gets destroyed after deleting something)
- Fixes a few issues with the Auth Http Service (I noticed that key refreshing did not work reliably, which should now be fixed)

# Screenshots
grafik
grafik
grafik

grafik
grafik

grafik
grafik
grafik
grafik

grafik
grafik

grafik

### CODE REVIEW

**Comment by MBuchalik** [comment]
In https://github.com/osrgroup/msadoc/blob/main/docs/api-keys.md we talk about the API Keys. But I was not really sure what we should document here. @georg-schwarz should we document how to use the UI here? Or did you have something else in mind?

**Comment by georg-schwarz** [comment]
You can leave that documentation stuff to me if u want ;) I'll handle it in a different PR

**Comment by MBuchalik** [comment]
> You can leave that documentation stuff to me if u want ;) I'll handle it in a different PR

Sounds good! Let's do it this way 👍

**Review by georg-schwarz — APPROVED** [review]
Looks great!

**Pull request merged**
